### ISSUE TITLE
e2e test failure tracking issue

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1450]
Please post here any occurrences of intermittent e2e test failure.

Thanks

**Comment by tcharding** [comment]
```
  Test btsieve API - bitcoin

    Bitcoin

      Transactions

        1) btsieve should respond not found when getting a non-existent bitcoin transaction query

  0 passing (354ms)

  1 failing

  1) Test btsieve API - bitcoin

       Bitcoin

         Transactions

           btsieve should respond not found when getting a non-existent bitcoin transaction query:

      AssertionError: expected { Object (domain, _events, ...) } to have status code 404 but got 400

      + expected - actual

      -400

      +404

      

      at Context.<anonymous> (btsieve/bitcoin_only/test.ts:31:41)

      at Generator.next (<anonymous>)

      at fulfilled (btsieve/bitcoin_only/test.ts:5:58)

      at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by thomaseizinger** [comment]
Please post a link to the CI run, otherwise it is impossible to investigate :)

**Comment by bonomat** [comment]
I would only use a tracking ticket if we have multiple e2e test failures, otherwise I would just have 1 ticket per failing tests. 
Let's close this and reopen a new ticket if the test fails again. 
If it does, attach the logs please so that we have something to investigate.
